apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample-pod
spec:
  containers:
    - name: sample
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']